DATABASE_ADAPTER: 'postgresql'
DATABASE_USERNAME: 'postgres'
DATABASE_PASSWORD: 'apps'
DATABASE_NAME: 'subscription_system'

GOOGLE_CLIENT_ID: '479331508044-pd9ooa45d3qin5lh72rubvjikd9mhsgp.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET: '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'
GOOGLE_REDIRECT_URL: 'http://0.0.0.0:3000/googles/api/v1/callback'
GOOGLE_SCOPES: 'email profile openid'
GOOGLE_AUTH_URL: 'https://accounts.google.com/o/oauth2/v2/auth'
GOOGLE_TOKEN_URL: